baseURL = 'http://openvoiceos.org/'
copyright = "{year}"
languageCode = 'en-US'
defaultContentLanguage = 'en'
theme = 'enchanted-lowkey'
title = 'Open Voice OS'
enableRobotsTXT = true
summaryLength = 15
paginate = 5


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
